initial development of CRUD collections
Deltares-research/stac-dms pull request #11
Opened 2024-07-26 14:29 UTC by grijzea

2024-07-26 14:33 UTC, grijzea commented
Het volgende viel mijn op tijdens het ontwikkelen
1) het endpoint collections heeft na een create/update pas na een seconde de nieuwe/aangepaste collectie beschikbaar. Ik vermoed dat dit komt door opensearch. Dit is een database maar een searchengine. updates zijn niet altijd direct beschikbaar. Voor nu opgelost met een wait. Maar dit is iets voor Nathan
2) De gegenereerde types kon ik niet vinden. Voor nu zelf een Collection.ts gemaakt
3) Het endpoint collections geeft maximaal 10 collections terug. Of zie ik iets over het hoofd.

2024-07-29 07:29 UTC, RobertBroersma commented
1. Dat is idd een beetje vervelend. Nathan gebruikt voor de keywords ook een Postgres database, dus hij had het ook al over om de rest ook over te zetten. Ik vermoed dat dit nl. gewoon een limitatie is van OpenSearch. Ik heb een kleine aanpassing gedaan in de collections index die gebruik maakt van `useApi` en Nuxt's `refresh` method. Hierdoor krijg je initieel wel data te zien, en vult 'ie het later aan met eventueel nieuwe data.
2. Ik zou voor types altijd kijken naar de flow van de data. In het geval van je tabel komt de data nu uit `useApi`, welke getypete `data` teruggeeft dankzij de OpenAPI spec. Je zou die type direct kunnen gebruiken door gebruik te maken van `ReturnType` en `Awaited`, of gewoon de gegenereerde type importeren. Dat laatste heb ik nu gedaan in op de tabel pagina. op die manier zijn de types altijd in sync. Als de type dan veranderd in de backend zie je tijdens development al dat er iets mis gaat zijn!
3. Dat klopt. De STAC spec werkt met token pagination. Uit het endpoint krijg je ook een lijstje links terug, waarin ook (mogelijk) een met `rel=next`, dat is de endpoint voor de volgende pagina met items. Op die volgende pagina krijg je dan een link met `rel=prev`

2024-07-29 07:44 UTC, RobertBroersma requested changes
Klopt het dat je nog geen prettier gebruikt? Dat zou wel handig zijn voor consistente formatting.

Zou je ook alle console.log's eruit willen halen?

2024-07-29 07:44 UTC, RobertBroersma commented on frontend/components/collections/CollectionCard.vue
Misschien is het handig om in de naamgeving van dit component te reflecteren dat het om een formulier gaat

2024-07-29 07:44 UTC, RobertBroersma commented on frontend/components/collections/CollectionCard.vue
> +            <Button @click="emitChange">{{ buttonTitle }}</Button>
Ik denk dat je deze events aan de form submit moet koppelen. Als ik nu submit met ENTER bijv. werkt het niet

2024-07-29 07:44 UTC, RobertBroersma commented on frontend/nuxt.config.ts
> +  ssr: false,
Waarom?

2024-07-29 07:44 UTC, RobertBroersma commented on frontend/nuxt.config.ts
> +        schema: "http://localhost:8000/api/api",
Dit breekt de OpenAPI typegen in docker

2024-07-29 07:44 UTC, RobertBroersma commented on frontend/pages/admin.vue
> +      Adminstation of catalogues, collections and permissions.
Paar spelfoutjes op deze pagina

2024-07-29 07:44 UTC, RobertBroersma commented on frontend/pages/collections/index.vue
> +  router.push("/collections/update/" + id)
Hier zou je ook gewoon `NuxtLink`'s voor kunnen gebruiken

2024-07-30 11:40 UTC, merged